boot:
	rm -rf Boot.java
	echo "public class Boot{public static void main(String args[]){System.out.println(args.length);}}" >> Boot.java
	javac Boot.java
	java Boot 1 2 3
dependencies:
	git clone https://github.com/processing/processing4.git
	git clone https://github.com/AOSPA/android_build.git